### ISSUE TITLE
Secondary mark dataset broken if invalid state

### ISSUE THREAD

**Issue by sokrahta** [socrata-platform/spandex#63]
when catching `com.socrata.spandex.secondary.InvalidStateBeforeEvent` don't go into retries, just mark it broken

**Comment by sokrahta** [comment]
```scala
2015-09-04 16:50:33,042 INFO [Worker 5 for secondary spandex3] (igjkemjxqsn8yil3pgkgqn62) [DatasetId(63560)] SecondaryWatcher >> Syncing DatasetId(63560) into spandex3
2015-09-04 16:50:33,061 INFO [Worker 3 for secondary spandex3] (a3xcyjax7xcirpt894jbv3b9u) [DatasetId(63604)] VersionEventsHandler ColumnCreated event: adding column zipd-q8dx/6 to column map for dataset alpha.63604 copy 1
2015-09-04 16:50:33,070 INFO [Worker 1 for secondary spandex3] (9qj6nhk2twfspkeyzu9jrq7jw) [DatasetId(62863)] VersionEventsHandler ColumnCreated event: adding column kvjn-cez6/4 to column map for dataset alpha.62863 copy 1
2015-09-04 16:50:33,074 INFO [Worker 5 for secondary spandex3] (igjkemjxqsn8yil3pgkgqn62) [DatasetId(63560)] SecondaryWatcher playback-to-secondary/lookup-dataset: 30ms; [["dataset_id","DatasetId(63560)"]]
2015-09-04 16:50:33,074 INFO [Worker 5 for secondary spandex3] (igjkemjxqsn8yil3pgkgqn62) [DatasetId(63560)] PlaybackToSecondary Found dataset DatasetId(63560) in truth
2015-09-04 16:50:33,078 WARN [Worker 2 for secondary spandex3] (cjhurktw332lnapl1f2ukeo) [DatasetId(47893)] SecondaryWatcher Unexpected exception while updating dataset DatasetId(47893) in secondary spandex3, retrying in 300.0...
com.socrata.spandex.secondary.InvalidStateBeforeEvent: Expected latest copy to be Unpublished when receiving WorkingCopyPublished event. Actual: Published.
        at com.socrata.spandex.secondary.PublishHandler.go(PublishHandler.scala:9)
        at com.socrata.spandex.secondary.VersionEventsHandler$$anonfun$handle$2.apply(VersionEventsHandler.scala:37)
        at com.socrata.spandex.secondary.VersionEventsHandler$$anonfun$handle$2.apply(VersionEventsHandler.scala:22)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at com.socrata.spandex.secondary.VersionEventsHandler.handle(VersionEventsHandler.scala:22)
```
